fix: add missing <cstdint> includes
Without the change build fails on this week's `gcc-13` as:

    In file included from google/cloud/internal/curl_handle.cc:15:
    google/cloud/internal/curl_handle.h:107:8:
      error: 'int32_t' in namespace 'std' does not name a type
      107 |   std::int32_t GetResponseCode();
          |        ^~~~~~~

`gcc-13` cleaned up `<string>` not to include `<cstdint>` for
newer c++ standards. Hence the build failures.