fix(ci): ci builds don't have a PR number (#6572)
* fix(ci): ci builds don't have a PR number

On post-submit (ci) builds, we have no `${_PR_NUBMER}`, so we see
non-fatal errors in the logs like:

```
+ gcloud builds list --limit 1 '--format=value(id)' --filter 'tags=pr AND tags= AND tags=publish-docs AND substitutions.COMMIT_SHA != 2f69122b4f2b20c85e2e55c1b2c753c21a85d912 AND create_time > 2021-05-14T16:23:37.115578690Z'
ERROR: (gcloud.builds.list) Logical operator not expected [tags=pr AND tags= *HERE* AND tags=publish-docs AND substitutions.COMMIT_SHA != 2f69122b4f2b20c85e2e55c1b2c753c21a85d912 AND create_time > 2021-05-14T16:23:37.115578690Z].
+ exit 0
```

This PR will avoid those errors.

* changed to exit early if no PR number